version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./news_aggregator.db
      - NEWS_SOURCE_URL=https://lithosgraphein.com/
      - LOG_FILE=news_aggregator.log
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - .:/news-agg
      - ./news_aggregator.db:/news-agg/news_aggregator.db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  tests:
    build: .
    depends_on:
      - web
    entrypoint: >
      sh -c "PYTHONPATH=$(pwd) pytest tests/"